CREATE TABLE adsb(
id integer,
rcvr integer,
hassig bool,
icao text,
fseenasiso text,
tsecs double precision,
cmsgs integer,
alt integer,
galt integer,
altt integer,
tisb bool,
spd integer,
trak double precision,
trkh bool,
sqk double precision,
help text,
vsi integer,
vsit integer,
mil bool,
gnd text,
spdtyp integer,
callsus bool,
tt text,
trt integer,
inhg double precision,
lat double precision,
long double precision,
mlat bool,
resettrail text,
sig double precision,
talt double precision,
ttrk double precision,
call text,
sat double precision,
posstale text,
source text,
postime double precision,
elevation double precision,
altsp integer,
altmsl double precision,
spdgnd double precision,
spdgndrv double precision,
spdind double precision,
spdtru double precision,
trakgnd double precision,
trakhead double precision,
vsibaro double precision,
vsigeo double precision,
pid integer PRIMARY KEY,
height double precision,
ongnd bool,
atairport bool,
airport text,
fid integer
);

SELECT AddGeometryColumn('adsb', 'geometry', 4326, 'POINT', 2);
UPDATE adsb SET geometry = ST_SetSRID(ST_MakePoint(long, lat), 4326);